<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RVSKCH90LT" name="Default test" tests="3" failures="2" timestamp="9 Jan 2020 07:27:31 GMT" time="53.924" errors="0">
  <testcase name="testCase001" time="0.013" classname="com.rvsappiumautomation.testcases.FirstPage"/>
  <testcase name="testCase002" time="25.229" classname="com.rvsappiumautomation.testcases.FirstPage">
    <failure type="com.rvsappiumautomation.exception.ExceptionHandler" message="This test is failed because of the Exception in com.rvsappiumautomation.testcases.FirstPage.testCase002()
The reason of this exception is: Expected condition failed: waiting for visibility of element located by By.xpath: //android.widget.Button[@resource-id=&amp;apos;com.android.packageinstaller:id/permission_allow_button&amp;apos;] (tried for 25 second(s) with 500 milliseconds interval)">
      <![CDATA[com.rvsappiumautomation.exception.ExceptionHandler: This test is failed because of the Exception in com.rvsappiumautomation.testcases.FirstPage.testCase002()
The reason of this exception is: Expected condition failed: waiting for visibility of element located by By.xpath: //android.widget.Button[@resource-id='com.android.packageinstaller:id/permission_allow_button'] (tried for 25 second(s) with 500 milliseconds interval)
	at com.rvsappiumautomation.testcases.FirstPage.testCase002(FirstPage.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testCase002 -->
  <testcase name="testCase003" time="25.17" classname="com.rvsappiumautomation.testcases.FirstPage">
    <failure type="com.rvsappiumautomation.exception.ExceptionHandler" message="This test is failed because of the Exception in com.rvsappiumautomation.testcases.FirstPage.testCase003()
The reason of this exception is: Expected condition failed: waiting for visibility of element located by By.xpath: //android.widget.Button[@resource-id=&amp;apos;com.android.packageinstaller:id/permission_allow_button&amp;apos;] (tried for 25 second(s) with 500 milliseconds interval)">
      <![CDATA[com.rvsappiumautomation.exception.ExceptionHandler: This test is failed because of the Exception in com.rvsappiumautomation.testcases.FirstPage.testCase003()
The reason of this exception is: Expected condition failed: waiting for visibility of element located by By.xpath: //android.widget.Button[@resource-id='com.android.packageinstaller:id/permission_allow_button'] (tried for 25 second(s) with 500 milliseconds interval)
	at com.rvsappiumautomation.testcases.FirstPage.testCase003(FirstPage.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testCase003 -->
</testsuite> <!-- Default test -->
